#!/bin/sh

BIN="./bst"

########################################################################

main()
{
	compile

	if [ ! -f "$BIN" ]
	then
		echo "No such executable: $BIN"
		exit 1
	fi

	if [ ! -x "$BIN" ]
	then
		echo "$BIN is not executable"
		exit 1
	fi

	if [ ! -d tests ]
	then
		echo "No tests/ directory here. Are you in the right directory?"
		exit 1
	fi

	if [ $# -eq 0 ]
	then
		inFiles="*.in"
	elif [ $# -eq 1 ]
	then
		inFiles="$1.in"
	else
		echo "Usage: $0 [test number]"
		exit 1
	fi

	for tt in tests/$inFiles
	do
		t=`basename $tt .in`
		echo "------------------------------"
		echo "* Test $t"

		$(timeout 0.2 "./$BIN" < tests/$t.in > tests/$t.out)

		exit_status=$?
		if [ $exit_status -eq 139 ]
		then
			echo "> Failed - a segmentation fault occurred"
			echo "           run the program manually (i.e., $BIN < tests/$t.in) to debug"
		elif [ $exit_status -eq 124 ]
		then
			echo "> Failed - the program timed out (likely due to an infinite loop)"
			if [ -f tests/$t.exp ]
			then
				echo "           check differences between tests/$t.exp and tests/$t.out"
			fi
		elif [ ! -f tests/$t.exp ]
		then
			echo "> No expected output available"
			echo
			echo "> Check your output manually (in tests/$t.out)"
		elif diff -Z tests/$t.exp tests/$t.out > /dev/null
		then
			echo "> Passed"
		else
			echo "> Failed - check differences between tests/$t.exp and tests/$t.out"
		fi
		echo "------------------------------ "
		echo
	done
}

compile()
{
	echo "* Compiling..."
	echo
	make || exit 1
	echo
}

########################################################################

main "$@"

